title: "SGCCRfC Wiki"
description: "Scientific Grid Computing & Cloud Computing Resources for Community"
theme: jekyll-theme-cayman

markdown: kramdown
highlighter: rouge

# Required for GitHub Pages
plugins: []

# Set base URL for project pages
baseurl: "/SGCCRfC-Wiki"
url: "https://sgccrfc.github.io"

# Navigation links
nav:
  - name: "Home"
    link: /
  - name: "About"
    link: /about

