title: SGCCRfC Wiki
description: Scientific Grid Computing and Cloud Computing Resources for Community

theme: just-the-docs
url: "https://sgccrfc.github.io/SGCCRfC-Wiki"

# Logo
logo: "/SGCCRfC_logo.png"
favicon_ico: "/SGCCRfC_logo.png"

# Navigation
search_enabled: true
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "SGCCRfC Main Site":
    - "https://sgccrfc.org"

color_scheme: light

# Custom CSS
assets:
  sources:
    - assets/css

