title: "SGCCRfC Wiki"
description: "Scientific Grid & Cloud Computing Resources for Community"

theme: "just-the-docs"

url: "https://sgccrfc.github.io"
baseurl: "/SGCCRfC-Wiki"

# Enable search
search_enabled: true

# Add logo
logo: "/assets/img/logo.png"   # matches your folder

# Navigation order
nav_sort: case_insensitive

# Enable callouts
callouts:
  highlight:
    color: yellow
  info:
    color: blue
  note:
    color: purple
  warning:
    color: red

# Aux links (top-right)
aux_links:
  "SGCCRfC Main Site":
    - "https://sgccrfc.org"

# GitHub Pages required
markdown: kramdown
plugins: []

